language: python

python:
  - "2.7"
  - "3.4"

script:
  - python hello.py
  - python helloLori.py
  
#before_install:
# - pip install coverage
#  - cd python

#script: 
#  - nosetests -v --with-coverage