language: python

python:
  - "2.7"
  - "3.4"

script:
<<<<<<< HEAD
#  - python hello.py
#  - python helloJustin.py
   - python helloChris.py

  
#before_install:
# - pip install coverage
#  - cd python

#script: 
#  - nosetests -v --with-coverage